defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: 子どものためのプログラミング道場
subtitle: CoderDojo 立川
avatar: ../assets/images/1.jpg
github:
  owner_gravatar_url: https://github.com/CoderDojoTachikawa

# Side Menu Links
menu:
  - text: トップ
    link: /
    icon: ""

  - text: はじめての方へ
    link: /skills-and-offers
    icon: ""

  - text: CoderDojo について
    link: /skills-and-offers
    icon: ""

  - text: コミュニティ
    link: /contact
    icon: ""

  - text: メンバー募集
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter

# Google Analytics
google_analytics: UA-109369485-1

